[pytest]
testpaths = tests
# Coloca a raiz do repositório no sys.path para os imports "automation.tests.api.*"
pythonpath = ..
addopts = -v -s --html=report.html --self-contained-html

# Logging configuration
log_cli = true
log_cli_level = INFO
log_format = %(asctime)s - %(levelname)s - %(message)s
log_date_format = %Y-%m-%d %H:%M:%S